spring:
  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:
    driverClassName: org.h2.Driver